# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
	source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi


source $HOME/.zsh-source/aliases
source $HOME/.zsh-source/keybinding
source $HOME/.zsh-source/vars
source $HOME/.zsh-source/secrets
source $HOME/.zsh-source/functions


#Autojump
[[ -s $(brew --prefix)/etc/profile.d/autojump.sh ]] && . $(brew --prefix)/etc/profile.d/autojump.sh

# nvm
export NVM_DIR="/Users/austin/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm


export HOMEBREW_CASK_OPTS="--appdir=/Applications"
bindkey "^[[1;5C" forward-word
bindkey "^[[1;5D" backward-word
# The next line enables shell command completion for gcloud.
# source '/Users/austin/google-cloud-sdk/completion.zsh.inc'
#
# # The next line updates PATH for the Google Cloud SDK.
# source '/Users/austin/google-cloud-sdk/path.zsh.inc'
#
# # The next line enables shell command completion for gcloud.
# source '/Users/austin/google-cloud-sdk/completion.zsh.inc'
#
