#!/bin/bash

PREFIX='>>> '
COLOR_RESET=$(tput sgr0 2> /dev/null)
COLOR_INFO=$(tput setaf 6 2> /dev/null)
COLOR_OK=$(tput setaf 2 2> /dev/null)
COLOR_WARN=$(tput setaf 3 2> /dev/null)
COLOR_ERR=$(tput setaf 1 2> /dev/null)
COLOR_CMD=$(tput setaf 5 2> /dev/null)
BANNER_FMT="$COLOR_CMD$PREFIX%s %s %s$COLOR_RESET"
BANNER_EOL='\n'
PWD=$(pwd)
PREZTO_HOME="zgen/sorin-ionescu/prezto-master"
USRLOCAL="/usr/local/bin"

function banner {
	printf "$BANNER_FMT""$BANNER_EOL" "$COLOR_CMD$1" "$2" "$3"
}

function banner_info {
	printf "$BANNER_FMT""$BANNER_EOL" "$COLOR_CMD$COLOR_INFO" "$1"
}

function unlink {
	if [ -z "${2// }" ]; then
		rm -rf ${HOME}/.${1}
	else
		rm -rf ${HOME}/.${2}
	fi
}

function link {
	if [ -z "${2// }" ]; then
		banner_info "${1} -> ${1}"
		unlink "${1}"
		ln -s "${PWD}/${1}" "${HOME}/.${1}"
	else
		banner_info "${1} -> ${2}"
		unlink "${1}" "${2}"
		ln -s "${PWD}/${1}" "${HOME}/.${2}"
	fi
}

function link_git {
	link git/gitignore_global gitignore_global
	link git/gitconfig gitconfig
	link git_template
	ln -s "${PWD}/bin/git-commitmsg" "${USRLOCAL}/git-commitmsg"
}

function link_nvim {
	link nvim vim
	link nvim/init.vim vimrc
	link nvim "config/nvim"
	ln -s vim/bundles/ausokai/colors/ausokai.vim /usr/local/share/nvim/runtime/colors
}

function link_tmux {
	link tmux.conf
	link tmux
	tpm
}

function tpm {
	unlink tmux/plugins/tpm
	git clone https://github.com/tmux-plugins/tpm ${HOME}/.tmux/plugins/tpm
}

function link_zsh {
	git clone git@github.com:tarjoilija/zgen.git tmp-zgen
	unlink zgen
	mv tmp-zgen ${HOME}/.zgen
	link zgen/zshrc zshrc
	link zsh-source zsh-source
	source ${HOME}/.zshrc
	link_prompt
	source ${HOME}/.zshrc
}

function link_prompt {
	ln -s "${HOME}/.zgen/sorin-ionescu/prezto-master" "${HOME}/.zprezto"
	unlink $PREZTO_HOME/modules/prompt/external/pure
	unlink $PREZTO_HOME/modules/prompt/external/powerline
	unlink $PREZTO_HOME/modules/prompt/external/agnoster
	git clone git@github.com:agnoster/agnoster-zsh-theme.git ${HOME}/.$PREZTO_HOME/modules/prompt/external/agnoster
	git clone git@github.com:sindresorhus/pure.git ${HOME}/.$PREZTO_HOME/modules/prompt/external/pure
	git clone git@github.com:davidjrice/prezto_powerline.git ${HOME}/.$PREZTO_HOME/modules/prompt/external/powerline

}


case $1 in
zsh)
	link_zsh
	;;
nvim)
	link_nvim
	;;
tmux)
	link_tmux
	;;
git)
	link_git
	;;
all)
	link_git
	link_nvim
	link_zsh
	link_git
	;;
*)
	cat <<USAGE
$0 [command]
zsh		remove zsh related files and resource them
USAGE
	exit 64
	;;
esac
