#!/bin/bash

PREFIX='>>> '
COLOR_RESET=$(tput sgr0 2> /dev/null)
COLOR_INFO=$(tput setaf 6 2> /dev/null)
COLOR_OK=$(tput setaf 2 2> /dev/null)
COLOR_WARN=$(tput setaf 3 2> /dev/null)
COLOR_ERR=$(tput setaf 1 2> /dev/null)
COLOR_CMD=$(tput setaf 5 2> /dev/null)
BANNER_FMT="$COLOR_CMD$PREFIX%s %s %s$COLOR_RESET"
BANNER_EOL='\n'
PWD=$(pwd)
PREZTO_HOME="zgen/sorin-ionescu/prezto-master"
function banner {
	printf "$BANNER_FMT""$BANNER_EOL" "$COLOR_CMD$1" "$2" "$3"
}

function banner_info {
	printf "$BANNER_FMT""$BANNER_EOL" "$COLOR_CMD$COLOR_INFO" "$1"
}

function unlink {
	if [ -z "${2// }" ]; then
		rm -rf ${HOME}/.${1}
	else
		rm -rf ${HOME}/.${2}
	fi
}

function link {
	if [ -z "${2// }" ]; then
		banner_info "${1} -> ${1}"
		unlink "${1}"
		ln -s "${PWD}/${1}" "${HOME}/.${1}"
	else
		banner_info "${1} -> ${2}"
		unlink "${1}" "${2}"
		ln -s "${PWD}/${1}" "${HOME}/.${2}"
	fi
}

function link_zsh {
	git clone git@github.com:tarjoilija/zgen.git tmp-zgen
	unlink zgen
	mv tmp-zgen ${HOME}/.zgen
	link zgen/zshrc zshrc
	link zsh-source zsh-source
}

function link_prompt {
	ln -s "${HOME}/.zgen/sorin-ionescu/prezto-master" "${HOME}/.zprezto"
	unlink $PREZTO_HOME/modules/prompt/external/pure
	unlink $PREZTO_HOME/modules/prompt/external/powerline
	unlink $PREZTO_HOME/modules/prompt/external/agnoster
	git clone git@github.com:agnoster/agnoster-zsh-theme.git ${HOME}/.$PREZTO_HOME/modules/prompt/external/agnoster
	git clone git@github.com:sindresorhus/pure.git ${HOME}/.$PREZTO_HOME/modules/prompt/external/pure
	git clone git@github.com:davidjrice/prezto_powerline.git ${HOME}/.$PREZTO_HOME/modules/prompt/external/powerline

	link prompt_austin_setup "$PREZTO_HOME/modules/prompt/functions/prompt_austin_setup"
}


case $1 in
link)
	link_zsh
	;;
prompt)
	link_prompt
	;;
*)
	cat <<USAGE
$0 [command]
link		remove source files and symlink them to repo
USAGE
	exit 64
	;;
esac
