source "$HOME/.zinit/bin/zinit.zsh"
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit

# Load a few important annexes, without Turbo
# (this is currently required for annexes)
zinit light-mode for \
    zinit-zsh/z-a-rust \
    zinit-zsh/z-a-as-monitor \
    zinit-zsh/z-a-patch-dl \
    zinit-zsh/z-a-bin-gem-node

### End of Zinit's installer chunk
bindkey -e
bindkey "^[[1;5C" forward-word
bindkey "^[[1;5D" backward-word

zinit snippet PZT::modules/tmux
zinit snippet PZT::modules/environment
zinit snippet PZT::modules/terminal
zinit snippet PZT::modules/history
zinit snippet PZT::modules/utility
zinit snippet PZT::modules/completion


zinit ice svn; zinit snippet PZT::modules/fasd
zinit ice svn pick:"init.zsh"; zinit snippet PZT::modules/git
zinit ice svn; zinit snippet PZT::modules/docker

zinit light apriendeau/prezto-slim-prompt
zinit ice silent atload'prompt slim'
# load the prompt
zinit snippet PZT::modules/prompt

zinit snippet PZT::modules/helper/init.zsh

setopt promptsubst

