export ZPLUG_HOME=$HOME/.zplug
source $ZPLUG_HOME/init.zsh
export PATH=/usr/local/bin:/bin:/usr/bin:$PATH
export TERM=xterm-256color
export EVENT_NOKQUEUE=1
export NVM_DIR="/Users/austin/.nvm"
export HOMEBREW_CASK_OPTS="--appdir=/Applications"

zmodload zsh/zprof

zplug "zplug/zplug"

# Prezto framework
zplug "sorin-ionescu/prezto", \
  use:"init.zsh", \
  hook-build:"ln -s $ZPLUG_HOME/repos/sorin-ionescu/prezto ~/.zprezto"

zplug "apriendeau/prezto-slim-prompt", \
  from:github, \
  hook-build:"cp $ZPLUG_HOME/repos/apriendeau/prezto-slim-prompt/prompt_slim_setup $ZPLUG_HOME/repos/sorin-ionescu/prezto/modules/prompt/functions"

zstyle ':prezto:*:*' color 'yes'
zstyle ':prezto:load' pmodule \
  'history-substring-search' \
  'git' \
  'docker' \
  'environment' \
  'terminal' \
  'editor' \
  'history' \
  'directory' \
  'utility' \
  'completion' \
  'prompt' \
  'osx' \
  'python' \
  'fasd' \
  'tmux'

zstyle ':prezto:module:editor' key-bindings 'vi'
zstyle ':prezto:module:prompt' theme 'slim'

# Custom zsh configuration
zplug "~/.zsh", \
  use:"*.zsh", \
  from:local

zplug load

bindkey -e
bindkey "^[[1;5C" forward-word
bindkey "^[[1;5D" backward-word

export NVM_DIR="$HOME/.nvm"
[ -s "/usr/local/opt/nvm/nvm.sh" ] && . "/usr/local/opt/nvm/nvm.sh"  # This loads nvm
[ -s "/usr/local/opt/nvm/etc/bash_completion.d/nvm" ] && . "/usr/local/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion
export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"

ssh-add -A 2>/dev/null;

export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
eval "$(rbenv init -)"
