# load zgen
source "${HOME}/.zgen/zgen.zsh"

# check if there's no init script
if ! zgen saved; then
    echo "Creating a zgen save"

	zgen load apriendeau/prezto-slim-prompt

	# prezto options
    zgen prezto editor key-bindings 'vi'
    zgen prezto prompt theme 'slim'

	zgen prezto editor dot-expansion 'no'

	# prezto and modules
    zgen prezto
    zgen prezto git
	zgen prezto tmux
	zgen prezto osx
	zgen prezto homebrew
    zgen prezto command-not-found
    zgen prezto syntax-highlighting
	zgen prezto history-substring-search

	zgen load $HOME/.zsh-source/aliases
	zgen load $HOME/.zsh-source/keybinding
	zgen load $HOME/.zsh-source/vars
	zgen load $HOME/.zsh-source/secrets
	zgen load $HOME/.zsh-source/functions

	zgen save
fi

[[ -s $(brew --prefix)/etc/profile.d/autojump.sh ]] && . $(brew --prefix)/etc/profile.d/autojump.sh

export NVM_DIR="/Users/austin/.nvm"
export HOMEBREW_CASK_OPTS="--appdir=/Applications"
bindkey "^[[1;5C" forward-word
bindkey "^[[1;5D" backward-word
